INSERT
    IGNORE INTO `activity_week_of_first_monday_sport_item_online` (
        `user_id`,
        `week_num`,
        `start_time`,
        `end_time`,
        `type`,
        `total_activities`,
        `total_second`,
        `total_distance_meters`,
        `elev_gain`,
        `elev_loss`,
        `calories`,
        `avg_heart_rate_bpm`,
        `avg_max_heart_rate_bpm`,
        `avg_speed`,
        `avg_max_speed`,
        `avg_cadence`,
        `avg_max_cadence`,
        `cycle_avg_watt`,
        `avg_cycle_max_watt`,
        `total_weight_kg`,
        `total_reps`,
        `year_num`,
        `privacy_me`,
        `privacy_friend`,
        `privacy_group`,
        `privacy_coach`,
        `privacy_any`,
        `gmt_start_time`,
        `gmt_end_time`,
        `avg_climb_incline_ratio`,
        `max_100m_incline_ratio`,
        `min_100m_incline_ratio`,
        `total_hr_zone0_second`,
        `total_hr_zone1_second`,
        `total_hr_zone2_second`,
        `total_hr_zone3_second`,
        `total_hr_zone4_second`,
        `total_hr_zone5_second`,
        `total_elev_gain_second`,
        `total_elev_loss_second`,
        `avg_swolf`,
        `best_swolf`,
        `rowing_avg_watt`,
        `rowing_max_watt`,
        `total_plus_g_force_x`,
        `total_plus_g_force_y`,
        `total_plus_g_force_z`,
        `total_minus_g_force_x`,
        `total_minus_g_force_y`,
        `total_minus_g_force_z`,
        `max_g_force_x`,
        `max_g_force_y`,
        `max_g_force_z`,
        `mini_g_force_x`,
        `mini_g_force_y`,
        `mini_g_force_z`,
        `total_ftp_zone0_second`,
        `total_ftp_zone1_second`,
        `total_ftp_zone2_second`,
        `total_ftp_zone3_second`,
        `total_ftp_zone4_second`,
        `total_ftp_zone5_second`,
        `total_ftp_zone6_second`,
        `max_heart_rate_bpm`,
        `max_speed`,
        `max_cadence`,
        `cycle_max_watt`,
        `avg_estimate_ftp`,
        `total_swing_count`,
        `total_forehand_swing_count`,
        `total_backhand_swing_count`,
        `avg_swing_speed`,
        `max_swing_speed`,
        `personalized_activity_intelligence`,
        `total_activity_second`,
        `total_feedback_energy`,
        `region_code`,
        `gender`,
        `birthday`
    )
SELECT
    OLD.`user_id`,
    OLD.`week_num`,
    OLD.`start_time`,
    OLD.`end_time`,
    CASE
        OLD.`type`
        WHEN '1' THEN '45'
        WHEN '2' THEN '33'
        WHEN '3' THEN '54'
        WHEN '4' THEN '3'
        WHEN '5' THEN '44'
        WHEN '6' THEN '8'
        WHEN '7' THEN '86'
        ELSE OLD.`type`
    END AS `type`,
    OLD.`total_activities`,
    OLD.`total_second`,
    OLD.`total_distance_meters`,
    OLD.`elev_gain`,
    OLD.`elev_loss`,
    OLD.`calories`,
    OLD.`avg_heart_rate_bpm`,
    OLD.`avg_max_heart_rate_bpm`,
    OLD.`avg_speed`,
    OLD.`avg_max_speed`,
    OLD.`avg_cadence`,
    OLD.`avg_max_cadence`,
    OLD.`cycle_avg_watt`,
    OLD.`avg_cycle_max_watt`,
    OLD.`total_weight_kg`,
    OLD.`total_reps`,
    OLD.`year_num`,
    OLD.`privacy_me`,
    OLD.`privacy_friend`,
    OLD.`privacy_group`,
    OLD.`privacy_coach`,
    OLD.`privacy_any`,
    OLD.`gmt_start_time`,
    OLD.`gmt_end_time`,
    OLD.`avg_climb_incline_ratio`,
    OLD.`max_100m_incline_ratio`,
    OLD.`min_100m_incline_ratio`,
    OLD.`total_hr_zone0_second`,
    OLD.`total_hr_zone1_second`,
    OLD.`total_hr_zone2_second`,
    OLD.`total_hr_zone3_second`,
    OLD.`total_hr_zone4_second`,
    OLD.`total_hr_zone5_second`,
    OLD.`total_elev_gain_second`,
    OLD.`total_elev_loss_second`,
    OLD.`avg_swolf`,
    OLD.`best_swolf`,
    OLD.`rowing_avg_watt`,
    OLD.`rowing_max_watt`,
    OLD.`total_plus_g_force_x`,
    OLD.`total_plus_g_force_y`,
    OLD.`total_plus_g_force_z`,
    OLD.`total_minus_g_force_x`,
    OLD.`total_minus_g_force_y`,
    OLD.`total_minus_g_force_z`,
    OLD.`max_g_force_x`,
    OLD.`max_g_force_y`,
    OLD.`max_g_force_z`,
    OLD.`mini_g_force_x`,
    OLD.`mini_g_force_y`,
    OLD.`mini_g_force_z`,
    OLD.`total_ftp_zone0_second`,
    OLD.`total_ftp_zone1_second`,
    OLD.`total_ftp_zone2_second`,
    OLD.`total_ftp_zone3_second`,
    OLD.`total_ftp_zone4_second`,
    OLD.`total_ftp_zone5_second`,
    OLD.`total_ftp_zone6_second`,
    OLD.`max_heart_rate_bpm`,
    OLD.`max_speed`,
    OLD.`max_cadence`,
    OLD.`cycle_max_watt`,
    OLD.`avg_estimate_ftp`,
    OLD.`total_swing_count`,
    OLD.`total_forehand_swing_count`,
    OLD.`total_backhand_swing_count`,
    OLD.`avg_swing_speed`,
    OLD.`max_swing_speed`,
    OLD.`personalized_activity_intelligence`,
    OLD.`total_activity_second`,
    OLD.`total_feedback_energy`,
    p.`header_region_code` AS `region_code`,
    p.`gender` AS `gender`,
    STR_TO_DATE(p.`birthday`, '%Y%m%d') AS `birthday`
FROM
    `activity_week_of_first_monday` AS OLD
    LEFT JOIN `user_profile` AS p ON p.`user_id` = OLD.`user_id`
WHERE
    OLD.user_id IN (
        ##USER_ID##)
        AND OLD.year_num = ##YEAR##
        AND OLD.week_num >= ##WEEK##;