INSERT
    IGNORE INTO `activity_week_sport_item_online` (
        `user_id`,
        `week_num`,
        `start_time`,
        `end_time`,
        `type`,
        `total_activities`,
        `total_second`,
        `total_distance_meters`,
        `elev_gain`,
        `elev_loss`,
        `calories`,
        `avg_heart_rate_bpm`,
        `avg_max_heart_rate_bpm`,
        `avg_speed`,
        `avg_max_speed`,
        `avg_cadence`,
        `avg_max_cadence`,
        `cycle_avg_watt`,
        `avg_cycle_max_watt`,
        `total_weight_kg`,
        `total_reps`,
        `year_num`,
        `privacy_me`,
        `privacy_friend`,
        `privacy_group`,
        `privacy_coach`,
        `privacy_any`,
        `gmt_start_time`,
        `gmt_end_time`,
        `avg_climb_incline_ratio`,
        `max_100m_incline_ratio`,
        `min_100m_incline_ratio`,
        `total_hr_zone0_second`,
        `total_hr_zone1_second`,
        `total_hr_zone2_second`,
        `total_hr_zone3_second`,
        `total_hr_zone4_second`,
        `total_hr_zone5_second`,
        `total_elev_gain_second`,
        `total_elev_loss_second`,
        `avg_swolf`,
        `best_swolf`,
        `rowing_avg_watt`,
        `rowing_max_watt`,
        `total_plus_g_force_x`,
        `total_plus_g_force_y`,
        `total_plus_g_force_z`,
        `total_minus_g_force_x`,
        `total_minus_g_force_y`,
        `total_minus_g_force_z`,
        `max_g_force_x`,
        `max_g_force_y`,
        `max_g_force_z`,
        `mini_g_force_x`,
        `mini_g_force_y`,
        `mini_g_force_z`,
        `total_ftp_zone0_second`,
        `total_ftp_zone1_second`,
        `total_ftp_zone2_second`,
        `total_ftp_zone3_second`,
        `total_ftp_zone4_second`,
        `total_ftp_zone5_second`,
        `total_ftp_zone6_second`,
        `max_heart_rate_bpm`,
        `max_speed`,
        `max_cadence`,
        `cycle_max_watt`,
        `avg_estimate_ftp`,
        `total_swing_count`,
        `total_forehand_swing_count`,
        `total_backhand_swing_count`,
        `avg_swing_speed`,
        `max_swing_speed`,
        `personalized_activity_intelligence`,
        `total_activity_second`,
        `total_feedback_energy`,
        `region_code`,
        `gender`,
        `birthday`
    )
SELECT
    aw.`user_id`,
    aw.`week_num`,
    aw.`start_time`,
    aw.`end_time`,
    CASE
        aw.`type`
        WHEN '1' THEN '45'
        WHEN '2' THEN '33'
        WHEN '3' THEN '54'
        WHEN '4' THEN '3'
        WHEN '5' THEN '44'
        WHEN '6' THEN '8'
        WHEN '7' THEN '86'
        ELSE aw.`type`
    END AS `type`,
    aw.`total_activities`,
    aw.`total_second`,
    aw.`total_distance_meters`,
    aw.`elev_gain`,
    aw.`elev_loss`,
    aw.`calories`,
    aw.`avg_heart_rate_bpm`,
    aw.`avg_max_heart_rate_bpm`,
    aw.`avg_speed`,
    aw.`avg_max_speed`,
    aw.`avg_cadence`,
    aw.`avg_max_cadence`,
    aw.`cycle_avg_watt`,
    aw.`avg_cycle_max_watt`,
    aw.`total_weight_kg`,
    aw.`total_reps`,
    aw.`year_num`,
    aw.`privacy_me`,
    aw.`privacy_friend`,
    aw.`privacy_group`,
    aw.`privacy_coach`,
    aw.`privacy_any`,
    aw.`gmt_start_time`,
    aw.`gmt_end_time`,
    aw.`avg_climb_incline_ratio`,
    aw.`max_100m_incline_ratio`,
    aw.`min_100m_incline_ratio`,
    aw.`total_hr_zone0_second`,
    aw.`total_hr_zone1_second`,
    aw.`total_hr_zone2_second`,
    aw.`total_hr_zone3_second`,
    aw.`total_hr_zone4_second`,
    aw.`total_hr_zone5_second`,
    aw.`total_elev_gain_second`,
    aw.`total_elev_loss_second`,
    aw.`avg_swolf`,
    aw.`best_swolf`,
    aw.`rowing_avg_watt`,
    aw.`rowing_max_watt`,
    aw.`total_plus_g_force_x`,
    aw.`total_plus_g_force_y`,
    aw.`total_plus_g_force_z`,
    aw.`total_minus_g_force_x`,
    aw.`total_minus_g_force_y`,
    aw.`total_minus_g_force_z`,
    aw.`max_g_force_x`,
    aw.`max_g_force_y`,
    aw.`max_g_force_z`,
    aw.`mini_g_force_x`,
    aw.`mini_g_force_y`,
    aw.`mini_g_force_z`,
    aw.`total_ftp_zone0_second`,
    aw.`total_ftp_zone1_second`,
    aw.`total_ftp_zone2_second`,
    aw.`total_ftp_zone3_second`,
    aw.`total_ftp_zone4_second`,
    aw.`total_ftp_zone5_second`,
    aw.`total_ftp_zone6_second`,
    aw.`max_heart_rate_bpm`,
    aw.`max_speed`,
    aw.`max_cadence`,
    aw.`cycle_max_watt`,
    aw.`avg_estimate_ftp`,
    aw.`total_swing_count`,
    aw.`total_forehand_swing_count`,
    aw.`total_backhand_swing_count`,
    aw.`avg_swing_speed`,
    aw.`max_swing_speed`,
    aw.`personalized_activity_intelligence`,
    aw.`total_activity_second`,
    aw.`total_feedback_energy`,
    up.`header_region_code` AS `region_code`,
    up.`gender` AS `gender`,
    STR_TO_DATE(up.`birthday`, '%Y%m%d') AS `birthday`
FROM
    `activity_week` AS aw
    LEFT JOIN `user_profile` AS up ON aw.`user_id` = up.`user_id`
WHERE
    aw.user_id IN (
        ##USER_ID##)
        AND aw.year_num = ##YEAR##
        AND aw.week_num >= ##WEEK##;